# Copyright (c) 2019 Nordic Semiconductor ASA
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause

CONFIG_NCS_SAMPLES_DEFAULTS=y

# ==== 1. KHÓA CHẾ ĐỘ BIÊN DỊCH TỐI ƯU DUNG LƯỢNG & ĐIỆN NĂNG ====
CONFIG_SIZE_OPTIMIZATIONS=y

# ==== 2. QUẢN LÝ NĂNG LƯỢNG CHO DÒNG NRF54L ====
CONFIG_PM=y
CONFIG_PM_POLICY_DEFAULT=y

# ==== 3. CẤU HÌNH ĐỊNH TUYẾN LƯU TRỮ ZMS ====
CONFIG_FLASH=y
CONFIG_FLASH_MAP=y
CONFIG_SETTINGS=y
CONFIG_SETTINGS_ZMS=y
CONFIG_NVS=n

# Cấu hình chung ứng dụng
CONFIG_NCS_APPLICATION_BOOT_BANNER_STRING="Leaf Node"
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=2048
CONFIG_HWINFO=y
CONFIG_DK_LIBRARY=y
CONFIG_SOC_FLASH_NRF_PARTIAL_ERASE=n

# ==== 4. BLUETOOTH MESH CƠ BẢN ====
CONFIG_BT=y
CONFIG_BT_DEVICE_NAME="Leaf Node"
CONFIG_BT_L2CAP_TX_BUF_COUNT=8
CONFIG_BT_OBSERVER=y
CONFIG_BT_PERIPHERAL=y
CONFIG_BT_SETTINGS=y
CONFIG_BT_RX_STACK_SIZE=2700

# Hạ dòng tĩnh: Tắt Controller phụ trợ
CONFIG_BT_CTLR_LE_ENC=n
CONFIG_BT_PHY_UPDATE=n
CONFIG_BT_CTLR_CHAN_SEL_2=n
CONFIG_BT_CTLR_MIN_USED_CHAN=n
CONFIG_BT_CTLR_PRIVACY=n

CONFIG_BT_MESH=y
CONFIG_BT_MESH_RELAY=n
CONFIG_BT_MESH_FRIEND=y
CONFIG_BT_MESH_TX_SEG_MAX=10
CONFIG_BT_MESH_PB_GATT=y
CONFIG_BT_MESH_GATT_PROXY=y
CONFIG_BT_MESH_PROXY_USE_DEVICE_NAME=y
CONFIG_BT_MESH_DK_PROV=y
CONFIG_BT_MESH_ONOFF_SRV=y
CONFIG_BT_MESH_CRPL=32
CONFIG_BT_MESH_MSG_CACHE_SIZE=32

# Giảm công suất phát RF xuống mức thấp nhất
CONFIG_BT_CTLR_TX_PWR_DYNAMIC_CONTROL=y
CONFIG_BT_CTLR_TX_PWR_ANTENNA=-4

CONFIG_GPIO=y
CONFIG_TICKLESS_KERNEL=y
CONFIG_WATCHDOG=n

# ==== 5. CẤU HÌNH GRTC ====
CONFIG_NRFX_GRTC=y
CONFIG_SYS_CLOCK_HW_CYCLES_PER_SEC=1000000
CONFIG_BT_MESH_ONOFF_CLI=y

# ====================================================================
# ==== 6. CẤU HÌNH LOGGING & RTT TỐI ĐA (HIỂN THỊ ĐẦY ĐỦ RELAY) ====
# ====================================================================

# Tắt hoàn toàn UART Console vật lý để tránh dòng rò và tránh kẹt Log
CONFIG_SERIAL=n
CONFIG_UART_CONSOLE=n
CONFIG_STDOUT_CONSOLE=n

# Bật hệ thống Log chung và ép luồng xuất ra SEGGER RTT
CONFIG_LOG=y
CONFIG_LOG_MODE_DEFERRED=y
CONFIG_USE_SEGGER_RTT=y
CONFIG_RTT_CONSOLE=y
CONFIG_PRINTK=y
CONFIG_LOG_BACKEND_RTT=y
CONFIG_LOG_BACKEND_UART=n

# Bật Log mức độ sâu nhất (Debug) cho toàn bộ Mesh Stack
CONFIG_BT_MESH_LOG_LEVEL_DBG=y

# (QUAN TRỌNG) Ép bật Log riêng cho Tầng Mạng - nơi quyết định Relay
CONFIG_BT_MESH_NET_LOG_LEVEL_DBG=y

# Tăng tối đa kích thước bộ đệm RTT để Log không bị mất chữ khi sóng dồn dập
CONFIG_SEGGER_RTT_BUFFER_SIZE_UP=8192
CONFIG_LOG_BUFFER_SIZE=8192

# Tăng số lượng bộ đệm advertiser để đáp ứng chuỗi truyền lặp 7 gói tin
CONFIG_BT_MESH_ADV_BUF_COUNT=20