#
# Copyright (c) 2024 Nordic Semiconductor ASA
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#
################################################################################
# Application overlay - nrf54l15

CONFIG_SOC_FLASH_NRF_PARTIAL_ERASE=n
CONFIG_SPI_NOR=n
CONFIG_NVS=n
CONFIG_NVS_LOOKUP_CACHE=n
CONFIG_SETTINGS_NVS_NAME_CACHE=n
CONFIG_ZMS=y
CONFIG_SETTINGS_ZMS_SECTOR_COUNT=8
CONFIG_ZMS_LOOKUP_CACHE=y
CONFIG_ZMS_LOOKUP_CACHE_SIZE=512
CONFIG_SETTINGS_ZMS_NAME_CACHE=y
CONFIG_SETTINGS_ZMS_NAME_CACHE_SIZE=512
CONFIG_ZMS_LOOKUP_CACHE_FOR_SETTINGS=y






# ==== CẤU HÌNH XUNG NHỊP THẤP 32kHz CHUẨN NRF54L ====
CONFIG_CLOCK_CONTROL=y
CONFIG_CLOCK_CONTROL_NRF_K32SRC_XTAL=y

# nRF54L15 uses GRTC (Global Real-Time Counter) as the ultra-low-power system timer.
# SYSCOUNTER stays alive on 32.768kHz LFCLK so k_work/k_sleep wakeups survive Deep Sleep with ~1-2 uA consumption.
CONFIG_TICKLESS_KERNEL=y
CONFIG_NRF_GRTC_TIMER=y
CONFIG_NRF_GRTC_START_SYSCOUNTER=y

# ==== CẤU HÌNH TẮT SẠCH CỔNG DEBUG SWD & RTT LOGGING ĐỂ HẠ DÒNG TỪ 1.6mA XUỐNG VÀI uA ====
CONFIG_LOG=n
CONFIG_CONSOLE=n
CONFIG_SERIAL=n
CONFIG_UART_CONSOLE=n
CONFIG_STDOUT_CONSOLE=n
CONFIG_USE_SEGGER_RTT=n
CONFIG_LOG_BACKEND_RTT=n
CONFIG_PRINTK=n
CONFIG_BOOT_BANNER=n

# ==== TẮT NGUỒN TOÀN BỘ CÁC NGOẠI VI KHÔNG NỐI THỰC TẾ (I2C, SPI) ====
CONFIG_I2C=n
CONFIG_SPI=n
CONFIG_SPI_NOR=n

